# Generated by Django 3.0.7 on 2020-06-10 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klad',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad935496-8ffe-4f6c-a76a-8996a1ba0953'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='android',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b2b211b-88c3-4bc4-8e72-3621cc4de8ac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ios',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
